version: '3.4'

services:
  phoenix:
    build: .
    environment:
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_DATABASE: ${PG_DATABASE}
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
    volumes:
      - ./app:/app
    ports:
      - ${APP_PORT}:4000
    depends_on:
      - db
    command:
      - /entrypoint.sh
    working_dir: /app

  db:
    image: "postgres:12"
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      # Set a path where Postgres should store the data
      PGDATA: ${PG_DATA}
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

# Define the volumes
volumes:
  pgdata:
